require("core.plugin_config.treesitter")
require("core.plugin_config.fzf")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gruvbox")
require("core.plugin_config.nvim_tree")
require("core.plugin_config.formatter")
require("core.plugin_config.diagnostic")
require("core.plugin_config.statusline")
